site_name: API Tapestry
site_description: API Tools and Resources for Developers
site_url: https://www.apitapestry.net
use_directory_urls: true

#nav:
#    - Home: index.md
#    - Tools:
#        - API Explorer: tools/api-explorer.md
#        - API Tester: tools/api-tester.md
#        - API Documentation Generator: tools/api-doc-generator.md
#    - Resources:
#        - Tutorials: resources/tutorials.md
#        - Best Practices: resources/best-practices.md
#        - API News: resources/api-news.md
#    - About: about.md
#    - Contact: contact.md

theme:
  name: material
  features:
    - navigation.expand
#    - navigation.sections
    - navigation.tracking
#    - navigation.top
#    - navigation.tabs
    - header.autohide
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  font:
    text: Inter
    code: Roboto Mono

extra_css:
  - extra.css

extra:
  generator: false
