site_name: API Tapestry
site_description: API Tools and Resources for Developers
site_url: https://www.apitapestry.net
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.expand
#    - navigation.sections
    - navigation.tracking
#    - navigation.top
#    - navigation.tabs
    - header.autohide
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  font:
    text: Inter
    code: Roboto Mono

extra_css:
  - css/home.css

extra:
  generator: false
